### ISSUE TITLE
After Chassis init, first run of phpunit returns ElasticSearch errors

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-local-chassis#134]
Immediately following a `composer chassis init`, if ElasticPress has not yet been setup, the first run of `phpunit` returns ElasticSearch errors.

Steps to reproduce:
1. Create a new chassis local server with `composer chassis init`
2. After the local chassis is set up and running, run `phpunit`
3. See errors as the tests are getting set up.

The workaround for this issue is to run `wp elasticpress index --setup --network-wide` in the Chassis instance. However, ElasticPress and PHPUnit don't strictly have anything to do with each other and it seems like this should be set up already after the `init` so errors are not generated.

Expected behavior: 
PHPUnit runs with no warnings, notices or errors.

![Screen Shot 2021-04-15 at 12 20 18 PM](https://user-images.githubusercontent.com/991511/114918995-f8f76800-9de4-11eb-9141-5e4ac42f2fb8.png)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
These aren't really errors as such, they're benign - when setting up indexes ElasticPress will first try to delete the indexes or check if they exist, this correctly returns a 404 response but we report any non 2xx status code as an error. They'll be fixed by https://github.com/humanmade/altis-enhanced-search/issues/137 at any rate.

It's partly down to Chassis's default `WP_DEBUG` settings too.

**Comment by jazzsequence** [comment]
Yeah maybe not a bug per se, but it does seem like something that could be taken care of prior to the initial install, so that as soon as the environment is set up, ES is already indexed so that step is already taken care of.
