### ISSUE TITLE
Run without humanmade/platform_chassis_extension

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-chassis#86]
The `humanmade/platform_chassis_extension` extension is a hardcoded dependency. This makes sense for Altis projects, but for non-Altis projects this adds a large number of unneeded extensions.

I tried adding `humanmade/platform_chassis_extension` to the `disabled_extensions` configuration but this had no effect as it was still present in `extensions`.

Is there a way to prevent the `humanmade/platform_chassis_extension` extension being installed? Or can one be added?

_Background:_ I'm using `altis/local-chassis` on a non-Altis project to make use of its useful features such as having everything Chassis-related managed through a Composer dependency and composer.json configuration, along with `composer chassis secure` etc.

**Comment by roborourke** [comment]
Never really considered this would become that useful outside of the Altis context! I'd rather keep the scope of what we officially support to just Altis because of the potential for having to then support further non-Altis use cases and problems that could be project specific.

I don't think using `disabled_extensions` would work anyway in this case - that setting has to be implemented by each extension to uninstall or halt whatever services it adds. 
`platform_chassis_extension` just adds a bunch of dependencies which I don't think are ignored even if the extension is disabled, that's an upstream Chassis issue though.

In all honestly I'm not sure this is something we want to support directly. You have a few options:

- create a fork with the mods you want
- create an additional package that provides or overrides the chassis command in this package by extending the composer command class and overriding the function that generates the local config file

Going to close as `wontfix` for now but happy to continue the discussion.
